/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xingzhi.robot.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 图书状态
 *
 * Values: _0,_1,_2,_3,_4,_5
 */
@Serializable
enum class AssetStatusDto(val value: kotlin.Int) {

    @SerialName(value = "0")
    _0(0),

    @SerialName(value = "1")
    _1(1),

    @SerialName(value = "2")
    _2(2),

    @SerialName(value = "3")
    _3(3),

    @SerialName(value = "4")
    _4(4),

    @SerialName(value = "5")
    _5(5);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AssetStatusDto) "$data" else null

        /**
         * Returns a valid [AssetStatusDto] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AssetStatusDto? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

