/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xingzhi.robot.model

import com.xingzhi.robot.model.AssetStatusDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ctrlNo 控制号[id]
 * @param assetNo 资产编号[id+hw]
 * @param curShelfId 当前架位号（货位[hw]）
 * @param barcode 条形码
 * @param price 价格
 * @param priceVal 价格（分）
 * @param libId 馆藏地（库房编号[kfbh]）
 * @param lendable 是否可借
 * @param callNo 索书号
 * @param volume 卷期
 * @param bookType 图书类型
 * @param bookTypeName 图书类型名称
 * @param medium 载体形态(Marc)
 * @param status 
 * @param dueTime 应还时间
 * @param curShelfDescription 当前架位描述
 * @param areaNumber 货区编号[hqbh]
 * @param areaName 货区名称（货区编号[hqbh]的中文）
 * @param areaFloor 楼层（货区编号[hqbh]查表）
 */
@Serializable

data class AssetInfoDto (

    /* 控制号[id] */
    @SerialName(value = "ctrlNo")
    val ctrlNo: kotlin.String,

    /* 资产编号[id+hw] */
    @SerialName(value = "assetNo")
    val assetNo: kotlin.String,

    /* 当前架位号（货位[hw]） */
    @SerialName(value = "curShelfId")
    val curShelfId: kotlin.String,

    /* 条形码 */
    @SerialName(value = "barcode")
    val barcode: kotlin.String? = null,

    /* 价格 */
    @SerialName(value = "price")
    val price: kotlin.String? = null,

    /* 价格（分） */
    @SerialName(value = "priceVal")
    val priceVal: kotlin.Int? = null,

    /* 馆藏地（库房编号[kfbh]） */
    @SerialName(value = "libId")
    val libId: kotlin.String? = null,

    /* 是否可借 */
    @SerialName(value = "lendable")
    val lendable: kotlin.Boolean? = null,

    /* 索书号 */
    @SerialName(value = "callNo")
    val callNo: kotlin.String? = null,

    /* 卷期 */
    @SerialName(value = "volume")
    val volume: kotlin.String? = null,

    /* 图书类型 */
    @SerialName(value = "bookType")
    val bookType: kotlin.String? = null,

    /* 图书类型名称 */
    @SerialName(value = "bookTypeName")
    val bookTypeName: kotlin.String? = null,

    /* 载体形态(Marc) */
    @SerialName(value = "medium")
    val medium: kotlin.String? = null,

    @Contextual @SerialName(value = "status")
    val status: AssetStatusDto? = null,

    /* 应还时间 */
    @SerialName(value = "dueTime")
    val dueTime: kotlin.String? = null,

    /* 当前架位描述 */
    @SerialName(value = "curShelfDescription")
    val curShelfDescription: kotlin.String? = null,

    /* 货区编号[hqbh] */
    @SerialName(value = "areaNumber")
    val areaNumber: kotlin.String? = null,

    /* 货区名称（货区编号[hqbh]的中文） */
    @SerialName(value = "areaName")
    val areaName: kotlin.String? = null,

    /* 楼层（货区编号[hqbh]查表） */
    @SerialName(value = "areaFloor")
    val areaFloor: kotlin.String? = null

)

