/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xingzhi.robot.model

import com.xingzhi.robot.model.BaseCtrlInfoDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param list 
 * @param total 
 */
@Serializable

data class SearchInfoDto (

    @SerialName(value = "list")
    val list: kotlin.collections.List<BaseCtrlInfoDto>? = null,

    @SerialName(value = "total")
    val total: kotlin.Int? = null

)

