/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xingzhi.robot.model

import com.xingzhi.robot.model.ShelfInfoDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param targetUrl 
 * @param success 
 * @param message 
 * @param unAuthorizedRequest 
 * @param result 
 * @param totalCount 
 */
@Serializable

data class ShelfInfoDtoResponse (

    @SerialName(value = "targetUrl")
    val targetUrl: kotlin.String? = null,

    @SerialName(value = "success")
    val success: kotlin.Boolean? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "unAuthorizedRequest")
    val unAuthorizedRequest: kotlin.Boolean? = null,

    @SerialName(value = "result")
    val result: ShelfInfoDto? = null,

    @SerialName(value = "totalCount")
    val totalCount: kotlin.Int? = null

)

