# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: OpenAPI Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate the OpenAPI definition
        run: ./gradlew openApiValidate

      - name: Generate the OpenAPI package
        run: ./gradlew openApiGenerate

      - name: Build package
        run: ./gradlew build
